### ISSUE TITLE
Lab Won't Open

### ISSUE THREAD

**Issue by steeznation16** [learn-co-curriculum/dsc-1-12-08-exploring-our-data-lab#1]
![image](https://user-images.githubusercontent.com/42447356/48018730-9a9c0a80-e0ff-11e8-87df-2c86ada3853f.png)

Presents an error message reading:
Unreadable Notebook: /home/steeznation16/dsc-1-12-08-exploring-our-data-lab-online-ds-ft-100118/index.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

**Comment by ShakeelRaja** [comment]
couldn't replicate this error.  more details needed
